languages = {
    "ABAP (SAP)": 18,
    "ASP": 54,
    "Assembler": 98,
    "Brio": 14,
    "C": 99,
    "C++": 53,
    "C#": 59,
    "COBOL": 55,
    "Cognos Impromptu Scripts": 42,
    "Cross System Products (CSP)": 18,
    "Cool:Gen/IEF": 24,
    "Datastage": 65,
    "Excel": 191,
    "Focus": 45,
    "FoxPro": 35,
    "HTML": 40,
    "J2EE": 49,
    "Java": 53,
    "JavaScript": 53,
    "JCL": 48,
    "LINC II": 30,
    "Lotus Notes": 21,
    "Natural": 34,
    ".NET": 60,
    "Oracle": 40,
    "PACBASE": 32,
    "Perl": 15,
    "PL/I": 80,
    "PL/SQL": 35,
    "Powerbuilder": 28,
    "REXX": 80,
    "Sabretalk": 66,
    "SAS": 37,
    "Siebel": 60,
    "SLOGAN": 75,
    "SQL": 21,
    "VB.NET": 60,
    "Visual Basic": 44,
}

categories = {
    "Low-Level / System-Oriented Languages": 98.5,
    "Classical Procedural / Legacy Languages": 62.0,
    "Web / Enterprise Technologies": 51.2,
    "Modern General-Purpose / Object-Oriented Languages": 53.8,
    "4GL / Business Tools / Application Generators": 44.7,
    "Scripting / Automation Languages": 46.3,
    "Database / Query / Reporting Languages": 35.6,
}
